version: '2'

services:
  web:
    image: nginx:latest
    container_name: docker_php_1
    ports:
      - "88:80"
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - .:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
